apiVersion: v1
kind: Service
metadata:
  name: indykube-service
  labels:
    app: indykube-app
spec:
  type: LoadBalancer
  selector:
    app: indykube-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000